#数据源配置
spring:
  #数据源配置
  datasource:
    url: jdbc:mysql://yzinterface@39.105.43.204:3306/yzinterface
    username: yzinterface
    password: yzinterface
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

#MyBaris配置
mybatis:
  #实体类路径
  type-aliases-package: classpath:com/wzzm/order/pojo
  #Mapper文件路径
  mapper-locations: classpath:mapper/*.xml

#服务器配置
server:
  #端口配置
  port : 8080
