#默认使用配置
spring:
  profiles:
    active: dev

#公共配置与profiles选择无关 mapperLocations指的路径是src/main/resources
mybatis:
  mapperLocations: classpath:mapper/*.xml

---

#开发配置
spring:
  profiles: dev

  datasource:
    url: jdbc:mysql://yzinterface@39.105.43.204:3306/yzinterface?serverTimezone=GMT%2B8
    username: yzinterface
    password: yzinterface
    # 使用druid数据源
    driver-class-name: com.mysql.cj.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

---

spring:
  redis:
    #数据库索引
    database: 0
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        #最大连接数
        max-active: 8
        #最大空闲
        max-idle: 8
        #最小空闲
        min-idle: 0

server:
  port: 8080

# actuator监控
management:
  server:
    # 设置监控服务端口
    port: 8081
  health:
    mail:
      enabled: false
  endpoints:
    # 设置端点是否可用 默认只有shutdown可用
    enabled-by-default: true
    web:
      # 设置是否暴露端点 默认只有health和info可见
      exposure:
        # 包括所有端点
        include: "*" # 注意需要添加引号
        # 排除端点
        exclude: shutdown
---
#配置日志
logging:
  #配置日志文件路径
  level:
    xatu.zsl: debug #不同目录下的日志可配置不同级别
    org.springfromework.web: info
    org.hibernate: error
  #采用相对路径方式将日志文件输出到【log\myspringboot.log】
  file: log\myspringboot.log




